### ISSUE TITLE
dockerize

### ISSUE THREAD

**Issue by shakedown-street** [Punkweb/punkweb-boards#66]
https://howchoo.com/g/y2y1mtkznda/getting-started-with-docker-compose-and-django

**Comment by ffreitasalves** [comment]
Can I help with that?

**Comment by shakedown-street** [comment]
My man!  Thanks for the contribution!

**Comment by ffreitasalves** [comment]
Thanks for accepting it.
I was writing a blog post about Dockerization and wrote about this issue, I hope you don't mind. If you want to take a look at the content: https://fernandofreitasalves.com/dockerizing-django-for-development/

**Comment by shakedown-street** [comment]
I don't mind at all, very good read, I'll reference that article when I need to dockerize my other projects.  Thanks again.
