### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by cyrildoussin** [Punkweb/punkweb-boards#86]
I haven't been able to find any licensing information on the main site or in the repo.

My company is looking at forum software at the moment and as a django-based company, we'd be happy to contribute with pull requests, but we first need to ensure that we are allowed to clone/fork this code and use it in a commercial setting.

Could you please add a LICENSE file with the common license of your choosing? Thanks

**Comment by shakedown-street** [comment]
Go right ahead, sorry about that!  Happy to hear you and your team are considering contributing.  BSD License, adding right now.

**Comment by shakedown-street** [comment]
Just one note that I forgot to mention.  If you use punkweb-boards please don't hesitate to use our official forums as a means of communicating issues, questions, suggestions, feedback, or your general experience using it, whether it's a good or bad experience.  I'd love to hear any feedback.

**Comment by cyrildoussin** [comment]
Noted. And thank you very much!
